# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nahagToran' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  
  pod 'GooglePlaces'
  pod 'GoogleMaps'

  # Pods for nahagToran

end
